services:
  # ----------------------------------
  # MinIO Object Storage
  # ----------------------------------
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      
      # OIDC Configuration (uses the service name 'keycloak' and the standard port)
      MINIO_IDENTITY_OPENID_CONFIG_URL: http://keycloak:8080/realms/minio_realm/.well-known/openid-configuration
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio-client
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: nrb2E4DKOL7QmShrtTO1O7RERXeKt6UC
      MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"
      MINIO_IDENTITY_OPENID_SCOPES: openid,profile,email
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1:9001
      MINIO_IDENTITY_OPENID_REDIRECT_URI: http://127.0.0.1:9001/oauth_callback
      MINIO_IDENTITY_OPENID_DISPLAY_NAME: "Login with SSO"
      

    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - keycloak-network
    restart: unless-stopped

volumes:
  minio-data:
  keycloak-data:


networks:
  keycloak-network:
    name: keycloak-network
    external: true

